global:
  seed: 42
  samples: 2
  skip_actions:
    - set_color
    - dim
models:
 - model: Qwen3-0.6B
   provider: local
   max_concurrent_requests: 3
   max_retries: 1
 - model: openrouter/horizon-beta
   provider: openrouter
   max_concurrent_requests: 3
   max_retries: 1
 - model: mistralai/mistral-small-3.2-24b-instruct:free
   provider: openrouter
   max_concurrent_requests: 3
   max_retries: 1
#  - model: qwen/qwen3-4b:free
#    provider: openrouter
#    max_concurrent_requests: 3
#    max_retries: 1
#  - model: mistralai/mistral-small-3.1-24b-instruct:free
#    provider: openrouter
#    max_concurrent_requests: 3
#    max_retries: 1